version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '54.167.232.39'"
    volumes:
      - .:/lms_advanced
    ports:
      - '3000:3000'
    depends_on:
      - db
